name: clean_arch_template
description: Template for flutter project using clean arch

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  logger: ^1.1.0
  flutter_bloc: ^8.1.1
  injectable: ^2.1.0
  get_it: ^7.2.0
  beamer: ^1.5.0
  numberpicker: ^2.1.1
  dio: ^4.0.5
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.15
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1
  json_annotation: ^4.6.0
  provider: ^6.0.3
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  retrofit_generator: ^4.0.3+1
  injectable_generator: ^2.1.3
  json_serializable: ^6.3.1
  freezed: ^2.0.3+1

flutter:

  uses-material-design: true


  assets:
    - assets/translations/